adaptive: false
buffer_size: 88
crossover: false
genome_size: 236
n_constants: 2
n_functions: 12
n_generations: 100
n_in: 38
n_in_env: 36
n_individuals: 51
n_nodes: 50
n_out: 36
p_mut_functions: 0.1
p_mut_inputs: 0.1
p_mut_outputs: 0.3
run_name: connect4_trial
seed: 8
selection:
  elite_size: 5
  tour_size: 2
  type: tournament
solver: cgp
survival: truncation
yellow_strategy:
  greedy: 0
  greedy_expert: 100
  greedy_improved: 0
  greedy_intermediate: 0
